### ISSUE TITLE
add indie 1.0

### ISSUE THREAD

**Issue by scttcper** [scttcper/xm-playlist-backend#35]
recommended by @bbilbo 	

make sure it can be found on the current api used - example using pitbull globalization -
```sh
curl --request GET \
  --url 'http://player.siriusxm.com/rest/v2/experience/modules/get/deeplink?deepLinkId=PitbullsGlobalization&deepLink-type=live' \
  --header 'accept: application/json, text/plain, */*' 
```

link https://www.siriusxm.com/indie1.0

**Comment by bbilbo** [comment]
Yes, Indie 1.0 can be found there

curl --request GET \
  --url 'http://player.siriusxm.com/rest/v2/experience/modules/get/deeplink?deepLinkId=Indie10&deepLink-type=live' \
  --header 'accept: application/json, text/plain, */*' \
  --cookie 'X-Mountain-PausePoint=AE9BC91259E6AF2B478C823E1DCC7D9C%2524%2524%2524type!Live~ID!9389~timestamp!null; SXMBYPASSEXP=3710984902; SXMBYPASS=FA65EC7C6BB71A5B037B3AA3BE49CEEAE8F3DAB6EEC54DB2A8CEE661FA01E596; visid_incap_986702=oUI936pETkmDMtlYeUx8MPMxMV0AAAAAQUIPAAAAAAAiFWbxIcd52g0OAG1Krs26; nlbi_986702=jIUUa3DPTAqU9Oaswn04UwAAAACOfsPCjvRc5ZUOmjpjB%2Bpw; incap_ses_882_986702=wd1Ge4gsWl%2BLSflALH89DJKeRF0AAAAAyI1Dp1EsErCXYAqbdKg7vg%3D%3D'

**Comment by scttcper** [comment]
thanks @bbilbo! added

**Comment by bbilbo** [comment]
Thanks!
